[project]
name = "F-LMM"
version = "0.1.0"
description = "F-LMM: Grounding Frozen Large Multimodal Models"
requires-python = ">=3.10,<3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
python = "3.10" 